import { COPY_KEYS, type CopyPairKey } from "./types";

export const COPY_FIELD_LABELS: Record<CopyPairKey, string> = {
  skipToContent: "تخطي إلى المحتوى",
  navHome: "رابط الرئيسية",
  navAbout: "رابط النبذة",
  navPractice: "رابط مجالات العمل",
  navContact: "رابط التواصل",
  navAria: "اسم القائمة للقراءة الصوتية",
  language: "تسمية مبدّل اللغة",
  languageToggleArLabel: "زر العربية",
  languageToggleEnLabel: "زر الإنجليزية",
  openMenu: "فتح القائمة",
  closeMenu: "إغلاق القائمة",
  profileBadge: "شارة أعلى الصفحة",
  currentRole: "تسمية المنصب",
  locationLabel: "تسمية المقر",
  practiceHeading: "عنوان مجالات العمل",
  practiceIntro: "مقدمة مجالات العمل",
  viewAllPractice: "رابط كل المجالات",
  aboutHeading: "عنوان النبذة",
  aboutLead: "سطر تحت عنوان النبذة",
  homeCtaSecondary: "الزر الثاني في الصفحة الأولى",
  highlightsHeading: "عنوان الملامح",
  emptyHighlights: "رسالة إذا لم توجد ملامح",
  emptyPractice: "رسالة إذا لم توجد مجالات",
  glanceHeading: "عنوان بطاقة التعريف",
  experienceHeading: "عنوان المسار المهني",
  educationHeading: "عنوان التعليم",
  membershipsHeading: "عنوان العضويات",
  languagesHeading: "عنوان اللغات",
  approachHeading: "عنوان منهج العمل",
  approachText: "نص منهج العمل",
  contactEmail: "تسمية البريد",
  contactPhone: "تسمية الهاتف",
  contactLinkedin: "تسمية لينكدإن",
  contactAddress: "تسمية العنوان",
  notProvided: "نص إذا كان الحقل فارغاً",
  intakeHeading: "عنوان لوحة الطلب",
  intakeIntro: "مقدمة لوحة الطلب",
  formName: "تسمية حقل الاسم",
  formSubject: "تسمية حقل الموضوع",
  formPhone: "تسمية حقل الهاتف",
  formSubmit: "نص زر الإرسال",
  formMailtoHint: "تلميح بعد النموذج",
  formSuccess: "رسالة النجاح",
  formCopy: "زر نسخ الطلب",
  formCopied: "تم النسخ",
  formError: "رسالة الخطأ",
  required: "كلمة مطلوب",
  disclaimer: "إخلاء المسؤولية في أسفل الصفحة",
  footerRights: "عبارة الحقوق",
  notFoundTitle: "عنوان صفحة غير موجودة",
  notFoundHome: "زر العودة من صفحة غير موجودة",
};

export const COPY_GROUPS: { title: string; keys: CopyPairKey[] }[] = [
  {
    title: "القائمة ومبدّل اللغة",
    keys: [
      "skipToContent",
      "navHome",
      "navAbout",
      "navPractice",
      "navContact",
      "navAria",
      "language",
      "languageToggleArLabel",
      "languageToggleEnLabel",
      "openMenu",
      "closeMenu",
    ],
  },
  {
    title: "عناوين الصفحات والأزرار",
    keys: [
      "profileBadge",
      "aboutHeading",
      "aboutLead",
      "homeCtaSecondary",
      "currentRole",
      "locationLabel",
      "practiceHeading",
      "practiceIntro",
      "viewAllPractice",
      "highlightsHeading",
      "glanceHeading",
      "experienceHeading",
      "educationHeading",
      "membershipsHeading",
      "languagesHeading",
      "approachHeading",
      "approachText",
    ],
  },
  {
    title: "لوحة الطلب والرسائل",
    keys: [
      "intakeHeading",
      "intakeIntro",
      "formName",
      "formSubject",
      "formPhone",
      "formSubmit",
      "required",
      "formMailtoHint",
      "formSuccess",
      "formCopy",
      "formCopied",
      "formError",
      "contactEmail",
      "contactPhone",
      "contactLinkedin",
      "contactAddress",
      "notProvided",
      "emptyHighlights",
      "emptyPractice",
    ],
  },
  {
    title: "أسفل الصفحة وصفحة غير موجودة",
    keys: [
      "disclaimer",
      "footerRights",
      "notFoundTitle",
      "notFoundHome",
    ],
  },
];

export { COPY_KEYS };
